#!/bin/bash

set -e

git update-index -q --ignore-submodules --refresh
if ! git diff-files --quiet --ignore-submodules -- ; then
  dirty=1
fi
if ! git diff-index --cached --quiet HEAD --ignore-submodules -- ; then
  dirty=1
fi
if [[ $dirty -eq 1 ]] ; then
  printf "#FAIL unstaged/uncommited changes\n" >&2
  exit 1
fi

original_branch=$(git rev-parse --abbrev-ref HEAD)
trap "git reset -q --hard; git checkout -q $original_branch" EXIT

printf "generating gem index\n"
git checkout -q gems
git ls-files --with-tree master gems |xargs git checkout master
gem generate_index > /dev/null 2>&1
if ! git diff-files --quiet --ignore-submodules -- ; then
  git add .
  git commit -m 'generated index'
fi

printf "pushing to $(git config remote.origin.url)\n"
git push origin gems
